[package]
name = "multithreaded_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.30", features = ["full"] }
tonic = "0.9"
prost = "0.11"
prost-types = "0.11"

[build-dependencies]
tonic-build = "0.9"
